name: Gmail AI Processor - Daily Run

on:
  schedule:
    # Runs at 6 PM Singapore Time (SGT is UTC+8, so 10:00 UTC = 6:00 PM SGT)
    - cron: '0 10 * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  process-emails:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create credentials file
      env:
        CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
      run: |
        echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json
        
    - name: Run Gmail AI Processor
      env:
        # Gmail Configuration
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        
        # AI Configuration
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AI_MODEL: gpt-5
        
        # WhatsApp Configuration (Primary)
        CALLMEBOT_API_KEY: ${{ secrets.CALLMEBOT_API_KEY }}
        CALLMEBOT_PHONE: ${{ secrets.CALLMEBOT_PHONE }}
        
        # WhatsApp Configuration (Secondary)
        CALLMEBOT_API_KEY_2: ${{ secrets.CALLMEBOT_API_KEY_2 }}
        CALLMEBOT_PHONE_2: ${{ secrets.CALLMEBOT_PHONE_2 }}
        
        # Email Domain Filter
        EMAIL_DOMAIN: '@dovercourt.edu.sg'
        
      run: |
        python main.py
        
    - name: Clean up credentials
      if: always()
      run: |
        rm -f credentials.json token.json
